import Navbar from "@/components/Navbar";
import Player from "@/components/Player";
import StoreProvider from "./StoreProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Navbar />
          {children}
          <Player />
        </StoreProvider>
      </body>
    </html>
  );
}
